packages:
  - '.'

overrides:
  '@octokit/plugin-paginate-rest@>=1.0.0 <9.2.2': '>=9.2.2'
  '@octokit/request-error@>=1.0.0 <5.1.1': '>=5.1.1'
  '@octokit/request@>=1.0.0 <8.4.1': '>=8.4.1'
  marked@<4.0.10: '>=4.0.10'
  semantic-release@<=17.2.2: '>=17.2.3'
  semver-regex@<3.1.3: '>=3.1.3'
  semver-regex@<3.1.4: '>=3.1.4'
  undici@<6.23.0: '>=6.23.0'
